version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.0
  aws-s3: circleci/aws-s3@1.0.9
# Use a package of configuration called an orb.
jobs:
  setup_aws_cli:
      executor: aws-cli/default
      steps:
        - aws-cli/setup:
            aws-access-key-id: $AWS_ACCESS_KEY_ID
            aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
            aws-region: $AWS_DEFAULT_REGION
        - run:
            name: "Testing AWS configuration"
            command: |
              # Show what's there now
              aws configure list
              # Retrieve security groups
              current_security_group=$(aws ec2 describe-security-groups --profile profilename --group-id ${GROUP_ID})
  create_infrastructure:  # Choose any name, such as `build`
      # The primary container, where your job's commands will run
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout # check out the code in the project directory
        - run: 
            name: Create CloudFormation Stack
            command: |
              aws cloudformation deploy \
                --template-file .circleci/template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
workflows:
  # Name the workflow
  Create_InfraStructure_ByAndrew:
    jobs:
      - create_infrastructure
